version: '3.3'
services:
  treasure_service:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '50051:50051'
    environment:
      - PORT=50051
    networks:
      - treasure_network
    healthcheck:
      test: ["CMD-SHELL", "nc -z 127.0.0.1 50051 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
  envoy:
    build:
      context: ./envoy
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    depends_on:
      - treasure_service
    networks:
      - treasure_network
    restart: unless-stopped
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 120s
    volumes:
      - ./envoy/envoy.yaml:/etc/envoy/envoy.yaml
networks:
  treasure_network:
    driver: bridge
