version: '3.3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '50051:50051'
    environment:
      - PORT=50051
    networks:
      - treasure_network
    healthcheck:
      test: ['CMD', 'nc', '-z', 'localhost', '50051']
      interval: 30s
      timeout: 10s
      retries: 3
  envoy:
    build:
      context: ./envoy
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    depends_on:
      - backend
    networks:
      - treasure_network
    restart: unless-stopped
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    volumes:
      - ./envoy/envoy.yaml:/etc/envoy/envoy.yaml
networks:
  treasure_network:
    driver: bridge