// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: dailytreasure.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DailyTreasure_UpdatePosition_FullMethodName = "/dailytreasure.DailyTreasure/UpdatePosition"
	DailyTreasure_GetGameConfig_FullMethodName  = "/dailytreasure.DailyTreasure/GetGameConfig"
)

// DailyTreasureClient is the client API for DailyTreasure service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DailyTreasureClient interface {
	// Stream to send rover position and receive game state updates
	UpdatePosition(ctx context.Context, in *Position, opts ...grpc.CallOption) (*GameState, error)
	// Get initial game configuration
	GetGameConfig(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GameConfig, error)
}

type dailyTreasureClient struct {
	cc grpc.ClientConnInterface
}

func NewDailyTreasureClient(cc grpc.ClientConnInterface) DailyTreasureClient {
	return &dailyTreasureClient{cc}
}

func (c *dailyTreasureClient) UpdatePosition(ctx context.Context, in *Position, opts ...grpc.CallOption) (*GameState, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GameState)
	err := c.cc.Invoke(ctx, DailyTreasure_UpdatePosition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dailyTreasureClient) GetGameConfig(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GameConfig, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GameConfig)
	err := c.cc.Invoke(ctx, DailyTreasure_GetGameConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DailyTreasureServer is the server API for DailyTreasure service.
// All implementations must embed UnimplementedDailyTreasureServer
// for forward compatibility.
type DailyTreasureServer interface {
	// Stream to send rover position and receive game state updates
	UpdatePosition(context.Context, *Position) (*GameState, error)
	// Get initial game configuration
	GetGameConfig(context.Context, *Empty) (*GameConfig, error)
	mustEmbedUnimplementedDailyTreasureServer()
}

// UnimplementedDailyTreasureServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDailyTreasureServer struct{}

func (UnimplementedDailyTreasureServer) UpdatePosition(context.Context, *Position) (*GameState, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePosition not implemented")
}
func (UnimplementedDailyTreasureServer) GetGameConfig(context.Context, *Empty) (*GameConfig, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGameConfig not implemented")
}
func (UnimplementedDailyTreasureServer) mustEmbedUnimplementedDailyTreasureServer() {}
func (UnimplementedDailyTreasureServer) testEmbeddedByValue()                       {}

// UnsafeDailyTreasureServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DailyTreasureServer will
// result in compilation errors.
type UnsafeDailyTreasureServer interface {
	mustEmbedUnimplementedDailyTreasureServer()
}

func RegisterDailyTreasureServer(s grpc.ServiceRegistrar, srv DailyTreasureServer) {
	// If the following call pancis, it indicates UnimplementedDailyTreasureServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DailyTreasure_ServiceDesc, srv)
}

func _DailyTreasure_UpdatePosition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Position)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DailyTreasureServer).UpdatePosition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DailyTreasure_UpdatePosition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DailyTreasureServer).UpdatePosition(ctx, req.(*Position))
	}
	return interceptor(ctx, in, info, handler)
}

func _DailyTreasure_GetGameConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DailyTreasureServer).GetGameConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DailyTreasure_GetGameConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DailyTreasureServer).GetGameConfig(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// DailyTreasure_ServiceDesc is the grpc.ServiceDesc for DailyTreasure service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DailyTreasure_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dailytreasure.DailyTreasure",
	HandlerType: (*DailyTreasureServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdatePosition",
			Handler:    _DailyTreasure_UpdatePosition_Handler,
		},
		{
			MethodName: "GetGameConfig",
			Handler:    _DailyTreasure_GetGameConfig_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dailytreasure.proto",
}
